"""empty message

Revision ID: 38d0d63a89a7
Revises: eef99c4ff32d
Create Date: 2022-09-29 22:07:22.789667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d0d63a89a7'
down_revision = 'eef99c4ff32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_song_name', table_name='song')
    op.drop_table('song')
    op.drop_table('song_to_artist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_to_artist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('artist_id', sa.INTEGER(), nullable=True),
    sa.Column('song_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_song_name', 'song', ['name'], unique=False)
    # ### end Alembic commands ###
