"""empty message

Revision ID: 551b0f285263
Revises: a7ec4fed1eea
Create Date: 2022-09-29 20:56:21.992738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551b0f285263'
down_revision = 'a7ec4fed1eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('title', sa.String(length=64), nullable=True))
    op.add_column('event', sa.Column('date_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_event_date_time'), 'event', ['date_time'], unique=False)
    op.create_index(op.f('ix_event_title'), 'event', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_title'), table_name='event')
    op.drop_index(op.f('ix_event_date_time'), table_name='event')
    op.drop_column('event', 'date_time')
    op.drop_column('event', 'title')
    # ### end Alembic commands ###
