"""empty message

Revision ID: b8ed03e9c608
Revises: 844d62fdc082
Create Date: 2022-09-30 00:34:20.068319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ed03e9c608'
down_revision = '844d62fdc082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('hometown', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_artist_hometown'), 'artist', ['hometown'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artist_hometown'), table_name='artist')
    op.drop_column('artist', 'hometown')
    # ### end Alembic commands ###
