"""empty message

Revision ID: eef99c4ff32d
Revises: 551b0f285263
Create Date: 2022-09-29 21:01:45.139933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef99c4ff32d'
down_revision = '551b0f285263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_index('ix_artist_first_name', table_name='artist')
    op.drop_index('ix_artist_last_name', table_name='artist')
    op.create_index(op.f('ix_artist_name'), 'artist', ['name'], unique=False)
    op.drop_column('artist', 'first_name')
    op.drop_column('artist', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('last_name', sa.VARCHAR(length=64), nullable=True))
    op.add_column('artist', sa.Column('first_name', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_artist_name'), table_name='artist')
    op.create_index('ix_artist_last_name', 'artist', ['last_name'], unique=False)
    op.create_index('ix_artist_first_name', 'artist', ['first_name'], unique=False)
    op.drop_column('artist', 'name')
    # ### end Alembic commands ###
